/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/TheIconList copy.vue')['default']
    Movie: typeof import('./components/Movie.vue')['default']
    Publications: typeof import('./components/Publications.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Steps: typeof import('./components/steps.vue')['default']
    SubPageTitle: typeof import('./components/SubPageTitle.vue')['default']
    TheBackTop: typeof import('./components/TheBackTop.vue')['default']
    TheBreadcrumbs: typeof import('./components/TheBreadcrumbs.vue')['default']
    TheDownloadBtn: typeof import('./components/TheDownloadBtn.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheHeaderInfo: typeof import('./components/TheHeaderInfo.vue')['default']
    TheIconList: typeof import('./components/TheIconList.vue')['default']
    TheIconTitle: typeof import('./components/TheIconTitle.vue')['default']
    TheLoadng: typeof import('./components/TheLoadng.vue')['default']
    ThePageMinTitle: typeof import('./components/ThePageMinTitle.vue')['default']
    ThePageNav: typeof import('./components/ThePageNav.vue')['default']
  }
}
