/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Brand: typeof import('./components/healthcare-business/Brand.vue')['default']
    CompanyHistory: typeof import('./components/company-profile/CompanyHistory.vue')['default']
    CompanyProfileContent: typeof import('./components/company-profile/CompanyProfileContent.vue')['default']
    HealthcareBusinessItem: typeof import('./components/healthcare-business/HealthcareBusinessItem.vue')['default']
    IndexBusiness: typeof import('./components/IndexBusiness.vue')['default']
    IndexCustomers: typeof import('./components/IndexCustomers.vue')['default']
    IndexField: typeof import('./components/IndexField.vue')['default']
    IndexFirst: typeof import('./components/IndexFirst.vue')['default']
    Innovation: typeof import('./components/corporate-philosophy-management-policy/Innovation.vue')['default']
    Mission: typeof import('./components/corporate-philosophy-management-policy/Mission.vue')['default']
    PracticesGuidelines: typeof import('./components/corporate-philosophy-management-policy/PracticesGuidelines.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubPageTitle: typeof import('./components/SubPageTitle.vue')['default']
    TheBackTop: typeof import('./components/TheBackTop.vue')['default']
    TheBreadcrumbs: typeof import('./components/TheBreadcrumbs.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheHeaderInfo: typeof import('./components/TheHeaderInfo.vue')['default']
    ThePageNav: typeof import('./components/ThePageNav.vue')['default']
    Values: typeof import('./components/corporate-philosophy-management-policy/Values.vue')['default']
    Vision: typeof import('./components/corporate-philosophy-management-policy/Vision.vue')['default']
  }
}
