# name字段是 workflow 的名称
name: GitHub Actions Build and Deploy Demo
# on字段指定触发 workflow 的条件，通常是某些事件
# 这里的触发条件是push代码到master的时候触发
on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    # checkout@ 这里写你的分支名称
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: Publish
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: "dist"
          destination-github-username: "QrayTec"
          destination-repository-name: "bighandz-www-v2"
          user-email: saopipizhu@163.com
          target-branch: "gh-page"

      - name: Clear Target Branch
        run: |
          git clone https://github.com/QrayTec/bighandz-www-v2.git
          cd bighandz-www-v2
          git checkout --orphan new-branch
          git add .
          git commit -m "Clean branch"
          git branch -D gh-page  # 删除远程仓库的 gh-page 分支
          git branch -m gh-page
          git push origin gh-page -f